export type ListingFieldType = 'text' | 'textarea' | 'number' | 'select';

export interface ListingFieldDefinition {
  key: string;
  label: string;
  type: ListingFieldType;
  section: 'catalog' | 'technical' | 'commercial' | 'logistics';
  required?: boolean;
  options?: string[];
  placeholder?: string;
  helpText?: string;
}

export interface ListingTemplate {
  id: string;
  title: string;
  description: string;
  backendCategoryId: string;
  badge: string;
  fields: ListingFieldDefinition[];
}

export const UAE_EMIRATES = [
  'Abu Dhabi',
  'Dubai',
  'Sharjah',
  'Ajman',
  'Umm Al Quwain',
  'Ras Al Khaimah',
  'Fujairah',
];

export const LAUNCH_LISTING_TEMPLATES: ListingTemplate[] = [
  {
  id: 'laptops',
  title: 'Laptops',
  description: 'Performance laptops, ultrabooks, business machines, gaming rigs, creator devices, and premium refurbished laptops.',
  backendCategoryId: 'cat1',
  badge: 'Launch Core',

  fields: [
    // BASIC INFO
    {
      key: 'brand',
      label: 'Brand',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Apple',
        'Dell',
        'HP',
        'Lenovo',
        'ASUS',
        'Acer',
        'MSI',
        'Huawei',
        'Samsung',
        'Microsoft',
        'Razer',
        'Gigabyte',
        'Alienware',
        'Toshiba',
        'Fujitsu',
        'LG',
        'VAIO',
        'Chuwi',
        'Honor',
        'Other',
      ],
    },
    {
      key: 'series',
      label: 'Series',
      type: 'text',
      section: 'catalog',
      placeholder: 'MacBook Pro, ThinkPad, Latitude, Pavilion, Nitro, ROG...',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'A1502, X1 Carbon Gen 9, Latitude 5490, MacBook Air M2...',
    },
    {
      key: 'laptopType',
      label: 'Laptop Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Ultrabook',
        'Business Laptop',
        'Gaming Laptop',
        'Creator Laptop',
        '2-in-1 Convertible',
        'Student Laptop',
        'Workstation',
        'Everyday Laptop',
        'Chromebook',
        'MacBook',
        'Other',
      ],
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Silver, Space Gray, Black, Blue...',
    },

    // PROCESSOR
    {
      key: 'processorBrand',
      label: 'Processor Brand',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['Intel', 'AMD', 'Apple', 'Qualcomm', 'MediaTek', 'Other'],
    },
    {
      key: 'processorFamily',
      label: 'Processor Family',
      type: 'select',
      section: 'technical',
      options: [
        'Intel Core i3',
        'Intel Core i5',
        'Intel Core i7',
        'Intel Core i9',
        'Intel Core Ultra 5',
        'Intel Core Ultra 7',
        'Intel Core Ultra 9',
        'Intel Pentium',
        'Intel Celeron',
        'Intel Xeon',
        'AMD Ryzen 3',
        'AMD Ryzen 5',
        'AMD Ryzen 7',
        'AMD Ryzen 9',
        'AMD Athlon',
        'AMD Threadripper',
        'Apple M1',
        'Apple M2',
        'Apple M3',
        'Apple M4',
        'Snapdragon X',
        'Snapdragon X Plus',
        'Snapdragon X Elite',
        'Other',
      ],
    },
    {
      key: 'processorModel',
      label: 'Processor Model',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: 'i7-1260P, Ryzen 7 7840HS, M2 Pro, i5-8350U...',
    },
    {
      key: 'generation',
      label: 'Generation',
      type: 'text',
      section: 'technical',
      placeholder: '8th Gen, 10th Gen, 13th Gen, M2, Ryzen 7000 series...',
    },
    {
      key: 'processorSpeed',
      label: 'Processor Speed',
      type: 'text',
      section: 'technical',
      placeholder: '1.8GHz up to 4.7GHz',
    },
    {
      key: 'coreCount',
      label: 'Core Count',
      type: 'select',
      section: 'technical',
      options: ['2-Core', '4-Core', '6-Core', '8-Core', '10-Core', '12-Core', '14-Core', '16-Core', '24-Core'],
    },

    // MEMORY & STORAGE
    {
      key: 'ram',
      label: 'RAM',
      type: 'select',
      section: 'technical',
      required: true,
      options: [
        '2GB',
        '4GB',
        '6GB',
        '8GB',
        '12GB',
        '16GB',
        '18GB',
        '24GB',
        '32GB',
        '36GB',
        '48GB',
        '64GB',
        '96GB',
        '128GB',
      ],
    },
    {
      key: 'ramType',
      label: 'RAM Type',
      type: 'select',
      section: 'technical',
      options: ['DDR3', 'DDR4', 'DDR5', 'LPDDR4', 'LPDDR4X', 'LPDDR5', 'LPDDR5X', 'Unified Memory'],
    },
    {
      key: 'ramUpgradeable',
      label: 'RAM Upgradeable',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No', 'Partially'],
    },
    {
      key: 'storage',
      label: 'Primary Storage',
      type: 'select',
      section: 'technical',
      required: true,
      options: [
        '32GB',
        '64GB',
        '128GB',
        '160GB',
        '240GB',
        '250GB',
        '256GB',
        '320GB',
        '500GB',
        '512GB',
        '640GB',
        '750GB',
        '1TB',
        '1.5TB',
        '2TB',
        '4TB',
        '8TB',
      ],
    },
    {
      key: 'storageType',
      label: 'Primary Storage Type',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['HDD', 'SSD', 'NVMe SSD', 'eMMC', 'Hybrid'],
    },
    {
      key: 'secondaryStorage',
      label: 'Secondary Storage',
      type: 'select',
      section: 'technical',
      options: [
        'None',
        '32GB',
        '64GB',
        '128GB',
        '160GB',
        '240GB',
        '250GB',
        '256GB',
        '320GB',
        '500GB',
        '512GB',
        '640GB',
        '750GB',
        '1TB',
        '2TB',
        '4TB',
      ],
    },
    {
      key: 'secondaryStorageType',
      label: 'Secondary Storage Type',
      type: 'select',
      section: 'technical',
      options: ['None', 'HDD', 'SSD', 'NVMe SSD', 'Hybrid'],
    },
    {
      key: 'expandableStorage',
      label: 'Storage Upgrade Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // GRAPHICS
    {
      key: 'graphicsType',
      label: 'Graphics Type',
      type: 'select',
      section: 'technical',
      options: ['Integrated', 'Dedicated', 'Integrated + Dedicated'],
    },
    {
      key: 'graphicsBrand',
      label: 'Graphics Brand',
      type: 'select',
      section: 'technical',
      options: ['Intel', 'NVIDIA', 'AMD', 'Apple', 'Qualcomm', 'Other'],
    },
    {
      key: 'graphicsModel',
      label: 'Graphics Model',
      type: 'text',
      section: 'technical',
      placeholder: 'Intel Iris Xe, RTX 4060, Radeon 680M, M3 GPU...',
    },
    {
      key: 'graphicsMemory',
      label: 'Graphics Memory',
      type: 'select',
      section: 'technical',
      options: ['Shared', '2GB', '4GB', '6GB', '8GB', '10GB', '12GB', '16GB'],
    },

    // DISPLAY
    {
      key: 'screenSize',
      label: 'Screen Size',
      type: 'select',
      section: 'technical',
      required: true,
      options: [
        '10-inch',
        '11-inch',
        '12-inch',
        '13-inch',
        '13.3-inch',
        '14-inch',
        '15-inch',
        '15.6-inch',
        '16-inch',
        '16.1-inch',
        '17-inch',
        '17.3-inch',
        '18-inch',
      ],
    },
    {
      key: 'displayResolution',
      label: 'Display Resolution',
      type: 'select',
      section: 'technical',
      options: [
        'HD',
        'HD+',
        'Full HD',
        'Full HD+',
        '2K',
        '2.5K',
        '3K',
        '3.2K',
        '4K',
        'Retina',
        'Liquid Retina',
        'Liquid Retina XDR',
        'OLED 2.8K',
        'Other',
      ],
    },
    {
      key: 'displayType',
      label: 'Display Type',
      type: 'select',
      section: 'technical',
      options: ['LCD', 'IPS', 'TN', 'OLED', 'Mini LED', 'Retina', 'Touchscreen', 'Non-Touch'],
    },
    {
      key: 'refreshRate',
      label: 'Refresh Rate',
      type: 'select',
      section: 'technical',
      options: ['60Hz', '90Hz', '120Hz', '144Hz', '165Hz', '240Hz'],
    },
    {
      key: 'screenFinish',
      label: 'Screen Finish',
      type: 'select',
      section: 'technical',
      options: ['Matte', 'Glossy', 'Anti-Glare'],
    },

    // CONNECTIVITY & PORTS
    {
      key: 'wirelessConnectivity',
      label: 'Wireless Connectivity',
      type: 'text',
      section: 'technical',
      placeholder: 'Wi-Fi 6, Wi-Fi 6E, Bluetooth 5.3',
    },
    {
      key: 'usbPorts',
      label: 'USB Ports',
      type: 'text',
      section: 'technical',
      placeholder: '2 x USB-A, 2 x USB-C',
    },
    {
      key: 'videoPorts',
      label: 'Video Ports',
      type: 'text',
      section: 'technical',
      placeholder: 'HDMI, DisplayPort, Thunderbolt',
    },
    {
      key: 'audioPorts',
      label: 'Audio Ports',
      type: 'text',
      section: 'technical',
      placeholder: '3.5mm combo jack',
    },
    {
      key: 'cardReader',
      label: 'Card Reader',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No', 'microSD', 'SD Card'],
    },
    {
      key: 'ethernetPort',
      label: 'Ethernet Port',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // CAMERA / KEYBOARD / FEATURES
    {
      key: 'webcam',
      label: 'Webcam',
      type: 'text',
      section: 'technical',
      placeholder: '720p HD, 1080p FHD, 12MP Center Stage',
    },
    {
      key: 'keyboardType',
      label: 'Keyboard Type',
      type: 'select',
      section: 'technical',
      options: ['Standard', 'Backlit', 'RGB Backlit', 'Arabic Keyboard', 'English Keyboard', 'Arabic + English Keyboard'],
    },
    {
      key: 'fingerprintSensor',
      label: 'Fingerprint Sensor',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'faceUnlock',
      label: 'Face Unlock',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'touchscreenSupport',
      label: 'Touchscreen Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // BATTERY & POWER
    {
      key: 'batteryType',
      label: 'Battery Type',
      type: 'text',
      section: 'technical',
      placeholder: 'Lithium-Polymer',
    },
    {
      key: 'batteryLife',
      label: 'Battery Life',
      type: 'text',
      section: 'technical',
      placeholder: 'Up to 10 hours',
    },
    {
      key: 'batteryHealth',
      label: 'Battery Health',
      type: 'text',
      section: 'commercial',
      placeholder: '100%, 92%, Good, Service Recommended',
    },
    {
      key: 'chargerIncluded',
      label: 'Charger Included',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['Yes', 'No'],
    },
    {
      key: 'chargerType',
      label: 'Charger Type',
      type: 'text',
      section: 'technical',
      placeholder: 'USB-C, MagSafe, Barrel Charger',
    },

    // SOFTWARE
    {
      key: 'operatingSystem',
      label: 'Operating System',
      type: 'select',
      section: 'technical',
      options: [
        'Windows 11',
        'Windows 10',
        'Windows 8',
        'Windows 7',
        'macOS',
        'Chrome OS',
        'Linux',
        'DOS',
        'No OS',
      ],
    },
    {
      key: 'officeIncluded',
      label: 'Office / Productivity Apps',
      type: 'select',
      section: 'commercial',
      options: ['Included', 'Not Included', 'Trial Only'],
    },

    // CONDITION / COMMERCIAL
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: [
        'New',
        'Open Box',
        'Like New',
        'Used - Excellent',
        'Used - Good',
        'Refurbished',
      ],
    },
    {
      key: 'conditionGrade',
      label: 'Condition Grade',
      type: 'select',
      section: 'commercial',
      options: ['A+', 'A', 'B+', 'B', 'C'],
    },
    {
      key: 'boxIncluded',
      label: 'Box Included',
      type: 'select',
      section: 'commercial',
      options: ['Yes', 'No'],
    },
    {
      key: 'includedItems',
      label: 'Included Items',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Laptop, charger, cable, original box, sleeve...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '90 Days', '6 Months', '1 Year', '2 Years'],
    },
    {
      key: 'countryOfOrigin',
      label: 'Country of Origin',
      type: 'text',
      section: 'commercial',
      placeholder: 'China, USA, Vietnam',
    },

    // LOGISTICS
    {
      key: 'productWeight',
      label: 'Product Weight',
      type: 'text',
      section: 'logistics',
      placeholder: '1.24 kg',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
      placeholder: '2.4',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '35 x 25 x 6 cm',
    },
  ],
},

{
  id: 'desktops',
  title: 'Desktops',
  description: 'Gaming PCs, office desktops, all-in-one computers, creator workstations, and refurbished desktop systems.',
  backendCategoryId: 'cat1',
  badge: 'Performance Setup',

  fields: [
    // BASIC INFO
    {
      key: 'brand',
      label: 'Brand',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Apple',
        'Dell',
        'HP',
        'Lenovo',
        'ASUS',
        'Acer',
        'MSI',
        'Intel',
        'Microsoft',
        'Alienware',
        'Corsair',
        'Custom Build',
        'Other',
      ],
    },
    {
      key: 'series',
      label: 'Series',
      type: 'text',
      section: 'catalog',
      placeholder: 'OptiPlex, iMac, Pavilion, Legion Tower, ROG...',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'OptiPlex 7090, iMac 24, Pavilion TG01...',
    },
    {
      key: 'desktopType',
      label: 'Desktop Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Tower PC',
        'Mini PC',
        'All-in-One',
        'Gaming PC',
        'Workstation',
        'Office Desktop',
        'Student Desktop',
        'Creator PC',
        'Refurbished Desktop',
        'Other',
      ],
    },
    {
      key: 'formFactor',
      label: 'Form Factor',
      type: 'select',
      section: 'catalog',
      options: [
        'Full Tower',
        'Mid Tower',
        'Mini Tower',
        'Small Form Factor',
        'Mini PC',
        'All-in-One',
        'Micro PC',
      ],
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Black, Silver, White...',
    },

    // PROCESSOR
    {
      key: 'processorBrand',
      label: 'Processor Brand',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['Intel', 'AMD', 'Apple', 'Other'],
    },
    {
      key: 'processorFamily',
      label: 'Processor Family',
      type: 'select',
      section: 'technical',
      options: [
        'Intel Core i3',
        'Intel Core i5',
        'Intel Core i7',
        'Intel Core i9',
        'Intel Core Ultra 5',
        'Intel Core Ultra 7',
        'Intel Core Ultra 9',
        'Intel Pentium',
        'Intel Celeron',
        'Intel Xeon',
        'AMD Ryzen 3',
        'AMD Ryzen 5',
        'AMD Ryzen 7',
        'AMD Ryzen 9',
        'AMD Athlon',
        'AMD Threadripper',
        'Apple M1',
        'Apple M2',
        'Apple M3',
        'Apple M4',
        'Other',
      ],
    },
    {
      key: 'processorModel',
      label: 'Processor Model',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: 'i7-12700, Ryzen 7 5700X, M3...',
    },
    {
      key: 'generation',
      label: 'Generation',
      type: 'text',
      section: 'technical',
      placeholder: '12th Gen, Ryzen 7000, M3...',
    },
    {
      key: 'processorSpeed',
      label: 'Processor Speed',
      type: 'text',
      section: 'technical',
      placeholder: '3.6GHz up to 5.0GHz',
    },
    {
      key: 'coreCount',
      label: 'Core Count',
      type: 'select',
      section: 'technical',
      options: ['2-Core', '4-Core', '6-Core', '8-Core', '10-Core', '12-Core', '16-Core', '24-Core', '32-Core'],
    },

    // MOTHERBOARD / MEMORY
    {
      key: 'motherboard',
      label: 'Motherboard / Chipset',
      type: 'text',
      section: 'technical',
      placeholder: 'B660, Z790, X670, Proprietary Board',
    },
    {
      key: 'ram',
      label: 'RAM',
      type: 'select',
      section: 'technical',
      required: true,
      options: [
        '4GB',
        '8GB',
        '12GB',
        '16GB',
        '24GB',
        '32GB',
        '48GB',
        '64GB',
        '96GB',
        '128GB',
      ],
    },
    {
      key: 'ramType',
      label: 'RAM Type',
      type: 'select',
      section: 'technical',
      options: ['DDR3', 'DDR4', 'DDR5', 'Unified Memory'],
    },
    {
      key: 'ramUpgradeable',
      label: 'RAM Upgradeable',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // STORAGE
    {
      key: 'storage',
      label: 'Primary Storage',
      type: 'select',
      section: 'technical',
      required: true,
      options: [
        '128GB',
        '240GB',
        '250GB',
        '256GB',
        '500GB',
        '512GB',
        '1TB',
        '2TB',
        '4TB',
        '8TB',
      ],
    },
    {
      key: 'storageType',
      label: 'Primary Storage Type',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['HDD', 'SSD', 'NVMe SSD', 'Hybrid'],
    },
    {
      key: 'secondaryStorage',
      label: 'Secondary Storage',
      type: 'select',
      section: 'technical',
      options: [
        'None',
        '128GB',
        '240GB',
        '250GB',
        '256GB',
        '500GB',
        '512GB',
        '1TB',
        '2TB',
        '4TB',
      ],
    },
    {
      key: 'secondaryStorageType',
      label: 'Secondary Storage Type',
      type: 'select',
      section: 'technical',
      options: ['None', 'HDD', 'SSD', 'NVMe SSD', 'Hybrid'],
    },

    // GRAPHICS
    {
      key: 'graphicsType',
      label: 'Graphics Type',
      type: 'select',
      section: 'technical',
      options: ['Integrated', 'Dedicated', 'Integrated + Dedicated'],
    },
    {
      key: 'graphicsBrand',
      label: 'Graphics Brand',
      type: 'select',
      section: 'technical',
      options: ['NVIDIA', 'AMD', 'Intel', 'Apple', 'Other'],
    },
    {
      key: 'graphicsModel',
      label: 'Graphics Model',
      type: 'text',
      section: 'technical',
      placeholder: 'RTX 4060, RTX 4070, Radeon RX 7800 XT, Intel UHD...',
    },
    {
      key: 'graphicsMemory',
      label: 'Graphics Memory',
      type: 'select',
      section: 'technical',
      options: ['Shared', '2GB', '4GB', '6GB', '8GB', '10GB', '12GB', '16GB', '24GB'],
    },

    // COOLING / POWER
    {
      key: 'coolingType',
      label: 'Cooling Type',
      type: 'select',
      section: 'technical',
      options: ['Air Cooling', 'Liquid Cooling', 'Stock Cooler', 'Custom Cooling'],
    },
    {
      key: 'powerSupply',
      label: 'Power Supply',
      type: 'text',
      section: 'technical',
      placeholder: '500W, 650W 80+ Bronze, 750W Gold',
    },

    // DISPLAY FOR ALL-IN-ONE
    {
      key: 'displayIncluded',
      label: 'Display Included',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'screenSize',
      label: 'Screen Size',
      type: 'text',
      section: 'technical',
      placeholder: '24-inch, 27-inch, N/A for tower PC',
    },
    {
      key: 'displayResolution',
      label: 'Display Resolution',
      type: 'select',
      section: 'technical',
      options: ['HD', 'Full HD', '2K', '4K', 'Retina', 'N/A'],
    },

    // CONNECTIVITY / PORTS
    {
      key: 'wirelessConnectivity',
      label: 'Wireless Connectivity',
      type: 'text',
      section: 'technical',
      placeholder: 'Wi-Fi 6, Bluetooth 5.2',
    },
    {
      key: 'usbPorts',
      label: 'USB Ports',
      type: 'text',
      section: 'technical',
      placeholder: '4 x USB-A, 2 x USB-C',
    },
    {
      key: 'videoPorts',
      label: 'Video Ports',
      type: 'text',
      section: 'technical',
      placeholder: 'HDMI, DisplayPort, VGA',
    },
    {
      key: 'audioPorts',
      label: 'Audio Ports',
      type: 'text',
      section: 'technical',
      placeholder: '3.5mm audio jack, mic input',
    },
    {
      key: 'ethernetPort',
      label: 'Ethernet Port',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // SOFTWARE
    {
      key: 'operatingSystem',
      label: 'Operating System',
      type: 'select',
      section: 'technical',
      options: [
        'Windows 11',
        'Windows 10',
        'Windows 8',
        'Windows 7',
        'macOS',
        'Linux',
        'DOS',
        'No OS',
      ],
    },
    {
      key: 'officeIncluded',
      label: 'Office / Productivity Apps',
      type: 'select',
      section: 'commercial',
      options: ['Included', 'Not Included', 'Trial Only'],
    },

    // INCLUDED ITEMS / COMMERCIAL
    {
      key: 'keyboardIncluded',
      label: 'Keyboard Included',
      type: 'select',
      section: 'commercial',
      options: ['Yes', 'No'],
    },
    {
      key: 'mouseIncluded',
      label: 'Mouse Included',
      type: 'select',
      section: 'commercial',
      options: ['Yes', 'No'],
    },
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: [
        'New',
        'Open Box',
        'Like New',
        'Used - Excellent',
        'Used - Good',
        'Refurbished',
      ],
    },
    {
      key: 'conditionGrade',
      label: 'Condition Grade',
      type: 'select',
      section: 'commercial',
      options: ['A+', 'A', 'B+', 'B', 'C'],
    },
    {
      key: 'includedItems',
      label: 'Included Items',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Desktop PC, power cable, keyboard, mouse...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '90 Days', '6 Months', '1 Year', '2 Years'],
    },

    // LOGISTICS
    {
      key: 'productWeight',
      label: 'Product Weight',
      type: 'text',
      section: 'logistics',
      placeholder: '6.5 kg',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
      placeholder: '8.0',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '50 x 25 x 45 cm',
    },
  ],
},


  {
  id: 'mobiles',
  title: 'Mobiles',
  description: 'Flagship smartphones, certified used phones, and UAE-ready handset listings.',
  backendCategoryId: 'cat2',
  badge: 'High Demand',

  fields: [
    // 📦 BASIC INFO
    {
      key: 'brand',
      label: 'Brand',
      type: 'select',
      section: 'catalog',
      required: true,
      options: ['Apple', 'Samsung', 'Google', 'Xiaomi', 'OnePlus', 'Huawei', 'Nothing', 'Oppo', 'Vivo'],
    },
    {
      key: 'model',
      label: 'Model',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'iPhone 15 Pro Max, Galaxy S24 Ultra...',
    },

    // 📱 DISPLAY
    {
      key: 'displaySize',
      label: 'Display Size',
      type: 'select',
      section: 'technical',
      options: ['5.5"', '6.1"', '6.5"', '6.7"', '6.8"'],
    },
    {
      key: 'displayType',
      label: 'Display Type',
      type: 'select',
      section: 'technical',
      options: ['OLED', 'AMOLED', 'Super Retina XDR', 'LCD'],
    },
    {
      key: 'refreshRate',
      label: 'Refresh Rate',
      type: 'select',
      section: 'technical',
      options: ['60Hz', '90Hz', '120Hz', '144Hz'],
    },

    // ⚙️ PERFORMANCE
    {
      key: 'processor',
      label: 'Processor',
      type: 'text',
      section: 'technical',
      placeholder: 'A17 Pro, Snapdragon 8 Gen 3',
    },
    {
      key: 'ram',
      label: 'RAM',
      type: 'select',
      section: 'technical',
      options: ['4GB', '6GB', '8GB', '12GB', '16GB'],
    },
    {
      key: 'storage',
      label: 'Storage',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['64GB', '128GB', '256GB', '512GB', '1TB'],
    },

    // 📸 CAMERA
    {
      key: 'rearCamera',
      label: 'Rear Camera',
      type: 'text',
      section: 'technical',
      placeholder: '48MP + 12MP + 12MP',
    },
    {
      key: 'frontCamera',
      label: 'Front Camera',
      type: 'text',
      section: 'technical',
      placeholder: '12MP',
    },
    {
      key: 'videoRecording',
      label: 'Video Recording',
      type: 'select',
      section: 'technical',
      options: ['1080p', '4K', '8K'],
    },

    // 🔋 BATTERY
    {
      key: 'battery',
      label: 'Battery Capacity',
      type: 'text',
      section: 'technical',
      placeholder: '4500mAh',
    },
    {
      key: 'fastCharging',
      label: 'Fast Charging',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // 🌐 CONNECTIVITY
    {
      key: 'network',
      label: 'Network',
      type: 'select',
      section: 'technical',
      options: ['4G', '5G'],
    },
    {
      key: 'simType',
      label: 'SIM Type',
      type: 'select',
      section: 'technical',
      options: ['Single SIM', 'Dual SIM', 'Nano SIM', 'eSIM', 'Dual SIM + eSIM'],
    },

    // 🔐 FEATURES
    {
      key: 'biometrics',
      label: 'Security',
      type: 'select',
      section: 'technical',
      options: ['Face ID', 'Fingerprint', 'Both'],
    },
    {
      key: 'os',
      label: 'Operating System',
      type: 'select',
      section: 'technical',
      options: ['iOS', 'Android'],
    },

    // 📦 COMMERCIAL
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used', 'Refurbished'],
    },
    {
      key: 'accessories',
      label: 'Accessories Included',
      type: 'text',
      section: 'commercial',
      placeholder: 'Cable, charger, box...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '6 Months', '1 Year'],
    },

    // 🚚 LOGISTICS
    {
      key: 'weight',
      label: 'Weight',
      type: 'text',
      section: 'logistics',
      placeholder: '221g',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '20 x 10 x 5 cm',
    },
  ],
},
  {
  id: 'tablets',
  title: 'Tablets',
  description: 'Work, family, and productivity tablets with WiFi and cellular options.',
  backendCategoryId: 'cat1',
  badge: 'Fast Moving',

  fields: [
    // 📦 BASIC INFO
    {
      key: 'brand',
      label: 'Brand',
      type: 'select',
      section: 'catalog',
      required: true,
      options: ['Apple', 'Samsung', 'Huawei', 'Lenovo', 'Xiaomi', 'Microsoft'],
    },
    {
      key: 'model',
      label: 'Model',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'iPad Pro 11, Galaxy Tab S9, Surface Go...',
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Space Gray, Silver, Black...',
    },

    // 📱 DISPLAY
    {
      key: 'screenSize',
      label: 'Screen Size',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['7-inch', '8-inch', '9-inch', '10.1-inch', '10.9-inch', '11-inch', '12.4-inch', '12.9-inch'],
    },
    {
      key: 'displayType',
      label: 'Display Type',
      type: 'select',
      section: 'technical',
      options: ['LCD', 'IPS LCD', 'OLED', 'AMOLED', 'Liquid Retina', 'Super Retina XDR'],
    },
    {
      key: 'resolution',
      label: 'Resolution',
      type: 'text',
      section: 'technical',
      placeholder: '2360 x 1640',
    },
    {
      key: 'refreshRate',
      label: 'Refresh Rate',
      type: 'select',
      section: 'technical',
      options: ['60Hz', '90Hz', '120Hz'],
    },

    // ⚙️ PERFORMANCE
    {
      key: 'processor',
      label: 'Processor',
      type: 'text',
      section: 'technical',
      placeholder: 'Apple M2, Snapdragon 8 Gen 2, Exynos...',
    },
    {
      key: 'ram',
      label: 'RAM',
      type: 'select',
      section: 'technical',
      options: ['3GB', '4GB', '6GB', '8GB', '12GB', '16GB'],
    },
    {
      key: 'storage',
      label: 'Storage',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['32GB', '64GB', '128GB', '256GB', '512GB', '1TB', '2TB'],
    },
    {
      key: 'expandableStorage',
      label: 'Expandable Storage',
      type: 'select',
      section: 'technical',
      options: ['No', 'Yes - microSD'],
    },

    // 🌐 CONNECTIVITY
    {
      key: 'connectivity',
      label: 'Connectivity',
      type: 'select',
      section: 'technical',
      required: true,
      options: ['WiFi', 'WiFi + Cellular', '5G Cellular'],
    },
    {
      key: 'bluetooth',
      label: 'Bluetooth',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'ports',
      label: 'Ports',
      type: 'text',
      section: 'technical',
      placeholder: 'USB-C, Lightning, 3.5mm jack',
    },

    // ✍️ TABLET-SPECIFIC FEATURES
    {
      key: 'stylusSupport',
      label: 'Stylus Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'keyboardSupport',
      label: 'Keyboard Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // 📸 CAMERA
    {
      key: 'rearCamera',
      label: 'Rear Camera',
      type: 'text',
      section: 'technical',
      placeholder: '12MP',
    },
    {
      key: 'frontCamera',
      label: 'Front Camera',
      type: 'text',
      section: 'technical',
      placeholder: '12MP Ultra Wide',
    },

    // 🔋 BATTERY
    {
      key: 'battery',
      label: 'Battery',
      type: 'text',
      section: 'technical',
      placeholder: '8000mAh / Up to 10 hours',
    },
    {
      key: 'charging',
      label: 'Charging Port',
      type: 'select',
      section: 'technical',
      options: ['USB-C', 'Lightning', 'Micro-USB'],
    },

    // 🖥️ SOFTWARE
    {
      key: 'operatingSystem',
      label: 'Operating System',
      type: 'select',
      section: 'technical',
      options: ['iPadOS', 'Android', 'Windows'],
    },

    // 💼 COMMERCIAL
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used', 'Refurbished'],
    },
    {
      key: 'batteryStatus',
      label: 'Battery Status',
      type: 'text',
      section: 'commercial',
      placeholder: 'Good, Excellent, 92% health',
    },
    {
      key: 'accessoriesIncluded',
      label: 'Accessories Included',
      type: 'text',
      section: 'commercial',
      placeholder: 'Cable, charger, stylus, keyboard case...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '6 Months', '1 Year'],
    },

    // 🚚 LOGISTICS
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '30 x 20 x 5 cm',
    },
  ],
},
  {
  id: 'mobile-accessories',
  title: 'Mobile Accessories',
  description: 'Chargers, cables, earbuds, cases, screen protectors, and power banks for smartphones.',
  backendCategoryId: 'cat-mobile-accessories',
  badge: 'High Demand',

  fields: [
    // BASIC INFO
    {
      key: 'accessoryType',
      label: 'Accessory Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Charger',
        'Cable',
        'Power Bank',
        'Earbuds',
        'Headphones',
        'Phone Case',
        'Screen Protector',
        'Car Charger',
        'Wireless Charger',
        'Adapter',
        'Holder / Stand',
      ],
    },
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Apple, Samsung, Anker, Baseus...',
    },
    {
      key: 'model',
      label: 'Model / Series',
      type: 'text',
      section: 'catalog',
      placeholder: 'MagSafe Charger, USB-C Cable, AirPods Pro...',
    },
    {
      key: 'compatibleDevices',
      label: 'Compatible Devices',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'iPhone 15 Pro Max, Samsung Galaxy S24, USB-C phones...',
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Black, White, Blue...',
    },

    // TECHNICAL
    {
      key: 'connectivityType',
      label: 'Connectivity Type',
      type: 'select',
      section: 'technical',
      options: [
        'Wired',
        'Wireless',
        'Bluetooth',
        'USB-C',
        'Lightning',
        'Micro-USB',
        'MagSafe',
      ],
    },
    {
      key: 'powerOutput',
      label: 'Power Output',
      type: 'text',
      section: 'technical',
      placeholder: '20W, 25W, 45W, 5000mAh, 10000mAh...',
    },
    {
      key: 'cableLength',
      label: 'Cable Length',
      type: 'text',
      section: 'technical',
      placeholder: '1m, 1.5m, 2m',
    },
    {
      key: 'material',
      label: 'Material',
      type: 'text',
      section: 'technical',
      placeholder: 'Silicone, TPU, Tempered Glass, Aluminum...',
    },
    {
      key: 'wirelessChargingSupport',
      label: 'Wireless Charging Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'fastChargingSupport',
      label: 'Fast Charging Support',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },

    // COMMERCIAL
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used'],
    },
    {
      key: 'packageContents',
      label: 'Package Contents',
      type: 'textarea',
      section: 'commercial',
      placeholder: '1 x charger, 1 x cable, user manual...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '6 Months', '1 Year'],
    },

    // LOGISTICS
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '20 x 10 x 5 cm',
    },
  ],
},

{
  id: 'laptop-accessories',
  title: 'Laptop Accessories',
  description: 'Laptop chargers, keyboards, mice, bags, docking stations, cooling pads, and productivity accessories.',
  backendCategoryId: 'cat-laptop-accessories',
  badge: 'Work Essentials',

  fields: [
    // BASIC INFO
    {
      key: 'accessoryType',
      label: 'Accessory Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Laptop Charger',
        'Keyboard',
        'Mouse',
        'Laptop Bag',
        'Sleeve / Case',
        'Docking Station',
        'USB Hub',
        'Cooling Pad',
        'Adapter',
        'External Hard Drive',
        'SSD Enclosure',
        'Monitor',
        'Webcam',
        'Laptop Stand',
      ],
    },
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Dell, HP, Logitech, Anker, Lenovo...',
    },
    {
      key: 'model',
      label: 'Model / Series',
      type: 'text',
      section: 'catalog',
      placeholder: 'Logitech MX Master 3, Dell 65W Charger...',
    },
    {
      key: 'compatibleDevices',
      label: 'Compatible Devices',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'MacBook Pro 14, Dell Latitude, USB-C laptops...',
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Black, Silver, Gray...',
    },

    // TECHNICAL
    {
      key: 'connectivityType',
      label: 'Connectivity Type',
      type: 'select',
      section: 'technical',
      options: [
        'Wired',
        'Wireless',
        'Bluetooth',
        'USB-A',
        'USB-C',
        'HDMI',
        'DisplayPort',
        '2.4GHz',
      ],
    },
    {
      key: 'powerRating',
      label: 'Power Rating',
      type: 'text',
      section: 'technical',
      placeholder: '45W, 65W, 90W, 120W',
    },
    {
      key: 'size',
      label: 'Size / Dimensions',
      type: 'text',
      section: 'technical',
      placeholder: '15.6-inch, Full Size, Compact...',
    },
    {
      key: 'material',
      label: 'Material',
      type: 'text',
      section: 'technical',
      placeholder: 'Fabric, Aluminum, Plastic, Leather...',
    },
    {
      key: 'ports',
      label: 'Ports / Interface',
      type: 'text',
      section: 'technical',
      placeholder: 'USB-C, HDMI, USB 3.0, SD card slot...',
    },
    {
      key: 'features',
      label: 'Key Technical Features',
      type: 'textarea',
      section: 'technical',
      placeholder: 'Backlit keyboard, silent click, fast transfer, ergonomic design...',
    },

    // COMMERCIAL
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used', 'Refurbished'],
    },
    {
      key: 'packageContents',
      label: 'Package Contents',
      type: 'textarea',
      section: 'commercial',
      placeholder: '1 x mouse, 1 x USB receiver, charging cable...',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '6 Months', '1 Year'],
    },

    // LOGISTICS
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '35 x 25 x 8 cm',
    },
  ],
},

  {
  id: 'clothing',
  title: 'Clothing',
  description: 'T-shirts, shirts, polos, hoodies, dresses, jeans, abayas, and fashion apparel with full color and size variants.',
  backendCategoryId: 'cat-fashion-clothing',
  badge: 'Fashion Core',

  fields: [
    // BASIC INFO
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Nike, Zara, H&M, Local Label',
    },
    {
      key: 'productType',
      label: 'Product Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'T-Shirt',
        'Shirt',
        'Polo',
        'Hoodie',
        'Sweatshirt',
        'Jacket',
        'Coat',
        'Dress',
        'Abaya',
        'Top',
        'Blouse',
        'Jeans',
        'Trousers',
        'Shorts',
        'Skirt',
        'Tracksuit',
        'Activewear',
        'Nightwear',
        'Innerwear',
        'Other',
      ],
    },
    {
      key: 'gender',
      label: 'Target Gender',
      type: 'select',
      section: 'catalog',
      required: true,
      options: ['Men', 'Women', 'Unisex', 'Kids'],
    },
    {
      key: 'ageGroup',
      label: 'Age Group',
      type: 'select',
      section: 'catalog',
      options: ['Adults', 'Kids', 'Toddlers', 'Babies'],
    },
    {
      key: 'styleCategory',
      label: 'Style Category',
      type: 'select',
      section: 'catalog',
      options: [
        'Casual',
        'Formal',
        'Office',
        'Streetwear',
        'Sportswear',
        'Loungewear',
        'Modest Wear',
        'Party Wear',
        'Traditional',
        'Other',
      ],
    },
    {
      key: 'occasion',
      label: 'Occasion',
      type: 'select',
      section: 'catalog',
      options: [
        'Daily Wear',
        'Office',
        'Sports',
        'Travel',
        'Party',
        'Wedding',
        'Ramadan / Eid',
        'Winter Wear',
        'Summer Wear',
      ],
    },

    // SIZE & FIT
    {
      key: 'sizeSystem',
      label: 'Size System',
      type: 'select',
      section: 'technical',
      options: ['International', 'EU', 'UK', 'US', 'Numeric'],
    },
    {
      key: 'availableSizes',
      label: 'Available Sizes',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: 'XS, S, M, L, XL, XXL',
    },
    {
      key: 'fit',
      label: 'Fit',
      type: 'select',
      section: 'technical',
      options: [
        'Slim Fit',
        'Regular Fit',
        'Relaxed Fit',
        'Oversized',
        'Tailored Fit',
        'Loose Fit',
      ],
    },
    {
      key: 'lengthType',
      label: 'Length Type',
      type: 'select',
      section: 'technical',
      options: [
        'Cropped',
        'Regular',
        'Longline',
        'Knee Length',
        'Midi',
        'Maxi',
        'Full Length',
      ],
    },

    // FABRIC & DESIGN
    {
      key: 'material',
      label: 'Material',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: '100% Cotton, Linen Blend, Polyester, Denim, Satin',
    },
    {
      key: 'fabricType',
      label: 'Fabric Type',
      type: 'select',
      section: 'technical',
      options: [
        'Cotton',
        'Polyester',
        'Linen',
        'Denim',
        'Wool',
        'Silk',
        'Satin',
        'Rayon',
        'Viscose',
        'Jersey',
        'Fleece',
        'Blend',
      ],
    },
    {
      key: 'fabricWeight',
      label: 'Fabric Weight / GSM',
      type: 'text',
      section: 'technical',
      placeholder: '180 GSM',
    },
    {
      key: 'stretch',
      label: 'Stretch',
      type: 'select',
      section: 'technical',
      options: ['Non-Stretch', 'Slight Stretch', 'Medium Stretch', 'High Stretch'],
    },
    {
      key: 'sleeveLength',
      label: 'Sleeve Length',
      type: 'select',
      section: 'technical',
      options: [
        'Sleeveless',
        'Short Sleeve',
        'Half Sleeve',
        'Three Quarter Sleeve',
        'Long Sleeve',
      ],
    },
    {
      key: 'neckline',
      label: 'Neckline / Collar',
      type: 'select',
      section: 'technical',
      options: [
        'Round Neck',
        'V-Neck',
        'Collared',
        'Polo Collar',
        'Mandarin Collar',
        'Boat Neck',
        'Hooded',
        'Other',
      ],
    },
    {
      key: 'pattern',
      label: 'Pattern',
      type: 'select',
      section: 'technical',
      options: [
        'Solid',
        'Printed',
        'Striped',
        'Checked',
        'Graphic',
        'Embroidered',
        'Floral',
        'Textured',
        'Other',
      ],
    },
    {
      key: 'closureType',
      label: 'Closure Type',
      type: 'select',
      section: 'technical',
      options: [
        'Pullover',
        'Button',
        'Zip',
        'Drawstring',
        'Elastic Waist',
        'Hook & Eye',
        'Open Front',
      ],
    },

    // COLOR & SEASON
    {
      key: 'primaryColor',
      label: 'Primary Color',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Black, White, Navy, Beige',
    },
    {
      key: 'secondaryColor',
      label: 'Secondary Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Optional accent color',
    },
    {
      key: 'season',
      label: 'Season',
      type: 'select',
      section: 'catalog',
      options: ['All Season', 'Summer', 'Winter', 'Spring', 'Autumn'],
    },

    // COMMERCIAL
    {
      key: 'careInstructions',
      label: 'Care Instructions',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Machine wash cold. Do not bleach. Iron on low heat.',
    },
    {
      key: 'countryOfOrigin',
      label: 'Country of Origin',
      type: 'text',
      section: 'commercial',
      placeholder: 'UAE, Turkey, India, China',
    },
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used - Excellent', 'Used - Good'],
    },
    {
      key: 'packageContents',
      label: 'Package Contents',
      type: 'textarea',
      section: 'commercial',
      placeholder: '1 x T-Shirt',
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days'],
    },

    // LOGISTICS
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
      placeholder: '0.35',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '30 x 25 x 4 cm',
    },
  ],
},

  {
  id: 'shoes',
  title: 'Shoes',
  description: 'Sneakers, sandals, heels, boots, and daily footwear with size, fit, and comfort details.',
  backendCategoryId: 'cat-fashion-shoes',
  badge: 'Footwear',

  fields: [
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Nike, Adidas, Puma, Local Label',
    },
    {
      key: 'productType',
      label: 'Shoe Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Sneakers',
        'Running Shoes',
        'Casual Shoes',
        'Formal Shoes',
        'Boots',
        'Sandals',
        'Slippers',
        'Heels',
        'Loafers',
        'Sports Shoes',
        'Other',
      ],
    },
    {
      key: 'gender',
      label: 'Target Gender',
      type: 'select',
      section: 'catalog',
      required: true,
      options: ['Men', 'Women', 'Unisex', 'Kids'],
    },
    {
      key: 'styleCategory',
      label: 'Style Category',
      type: 'select',
      section: 'catalog',
      options: ['Casual', 'Sports', 'Running', 'Office', 'Luxury', 'Outdoor', 'School', 'Party', 'Other'],
    },
    {
      key: 'primaryColor',
      label: 'Primary Color',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Black, White, Brown, Beige',
    },
    {
      key: 'upperMaterial',
      label: 'Upper Material',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: 'Leather, Mesh, Knit, PU, Suede',
    },
    {
      key: 'soleMaterial',
      label: 'Sole Material',
      type: 'text',
      section: 'technical',
      placeholder: 'Rubber, EVA, TPR, PVC',
    },
    {
      key: 'closureType',
      label: 'Closure Type',
      type: 'select',
      section: 'technical',
      options: ['Lace-Up', 'Slip-On', 'Velcro', 'Buckle', 'Zip', 'Open', 'Other'],
    },
    {
      key: 'sizeSystem',
      label: 'Size System',
      type: 'select',
      section: 'technical',
      options: ['EU', 'UK', 'US'],
    },
    {
      key: 'availableSizes',
      label: 'Available Sizes',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: '39, 40, 41, 42, 43',
    },
    {
      key: 'fitType',
      label: 'Fit Type',
      type: 'select',
      section: 'technical',
      options: ['True to Size', 'Runs Small', 'Runs Large', 'Wide Fit', 'Narrow Fit'],
    },
    {
      key: 'archSupport',
      label: 'Arch Support / Comfort',
      type: 'text',
      section: 'technical',
      placeholder: 'Memory foam insole, cushioned footbed',
    },
    {
      key: 'heelHeight',
      label: 'Heel / Sole Height',
      type: 'text',
      section: 'technical',
      placeholder: 'Flat, 3 cm, 5 cm',
    },
    {
      key: 'waterResistance',
      label: 'Water Resistance',
      type: 'select',
      section: 'technical',
      options: ['Yes', 'No'],
    },
    {
      key: 'careInstructions',
      label: 'Care Instructions',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Wipe clean with soft cloth. Do not machine wash.',
    },
    {
      key: 'countryOfOrigin',
      label: 'Country of Origin',
      type: 'text',
      section: 'commercial',
      placeholder: 'China, Vietnam, India, Turkey',
    },
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box', 'Like New', 'Used - Excellent', 'Used - Good'],
    },
    {
      key: 'packageContents',
      label: 'Package Contents',
      type: 'textarea',
      section: 'commercial',
      placeholder: '1 Pair of Shoes, 1 Box',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
      placeholder: '0.9',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '34 x 22 x 14 cm',
    },
  ],
},

  {
  id: 'beauty-makeup',
  title: 'Beauty / Makeup',
  description: 'Premium beauty, skincare, fragrance, and authentic cosmetics listings.',
  backendCategoryId: 'cat3',
  badge: 'GCC Ready',

  fields: [
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Maybelline, Huda Beauty, MAC, The Ordinary',
    },
    {
      key: 'productType',
      label: 'Product Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Foundation',
        'Lipstick',
        'Concealer',
        'Powder',
        'Blush',
        'Mascara',
        'Eyeliner',
        'Eyeshadow Palette',
        'Perfume',
        'Cleanser',
        'Serum',
        'Moisturizer',
        'Sunscreen',
        'Face Mask',
        'Gift Set',
        'Other',
      ],
    },
    {
      key: 'shade',
      label: 'Shade / Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'Warm Beige, Nude Pink, Ruby Red',
    },
    {
      key: 'finishType',
      label: 'Finish Type',
      type: 'select',
      section: 'technical',
      options: ['Matte', 'Dewy', 'Natural', 'Glossy', 'Satin', 'Radiant'],
    },
    {
      key: 'skinType',
      label: 'Skin Type Compatibility',
      type: 'select',
      section: 'technical',
      options: ['All Skin Types', 'Dry', 'Oily', 'Combination', 'Sensitive'],
    },
    {
      key: 'sizeVolume',
      label: 'Size / Volume',
      type: 'text',
      section: 'technical',
      required: true,
      placeholder: '30ml, 50ml, 100g',
    },
    {
      key: 'ingredients',
      label: 'Ingredients',
      type: 'textarea',
      section: 'technical',
      placeholder: 'Aqua, Glycerin, Niacinamide...',
    },
    {
      key: 'fragranceType',
      label: 'Fragrance Type',
      type: 'select',
      section: 'technical',
      options: ['Fragrance-Free', 'Floral', 'Woody', 'Fresh', 'Oriental', 'Sweet'],
    },
    {
      key: 'usageArea',
      label: 'Usage Area',
      type: 'select',
      section: 'technical',
      options: ['Face', 'Eyes', 'Lips', 'Body', 'Hair', 'Multi-Use'],
    },
    {
      key: 'expiryDate',
      label: 'Expiry Date',
      type: 'text',
      section: 'commercial',
      placeholder: 'MM/YYYY or ISO date',
    },
    {
      key: 'authenticityStatus',
      label: 'Authenticity Status',
      type: 'select',
      section: 'commercial',
      options: ['Authentic', 'Imported', 'Distributor Stock', 'Sealed Original'],
    },
    {
      key: 'usageInstructions',
      label: 'Usage Instructions',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Apply evenly on clean skin. For external use only.',
    },
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'New Sealed', 'Open Box'],
    },
    {
      key: 'countryOfOrigin',
      label: 'Country of Origin',
      type: 'text',
      section: 'commercial',
      placeholder: 'UAE, France, Korea, USA',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '18 x 12 x 6 cm',
    },
  ],
},

  {
  id: 'gifts-daily-use',
  title: 'Gifts / Daily Use',
  description: 'Giftables, home picks, and daily-use products for UAE-first household demand.',
  backendCategoryId: 'cat3',
  badge: 'Lifestyle',

  fields: [
    {
      key: 'category',
      label: 'Product Category',
      type: 'select',
      section: 'catalog',
      required: true,
      options: [
        'Gift Item',
        'Home Decor',
        'Kitchen Item',
        'Personal Use',
        'Office Use',
        'Travel Use',
        'Festival Gift',
        'Utility Product',
        'Other',
      ],
    },
    {
      key: 'productType',
      label: 'Product Type',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Mug, Gift Box, Organizer, Candle Set, Water Bottle',
    },
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      placeholder: 'Generic, Local Brand, Home Label',
    },
    {
      key: 'color',
      label: 'Color',
      type: 'text',
      section: 'catalog',
      placeholder: 'White, Gold, Pink, Black',
    },
    {
      key: 'usage',
      label: 'Usage / Occasion',
      type: 'select',
      section: 'catalog',
      options: ['Daily Use', 'Gift', 'Office', 'Travel', 'Ramadan', 'Eid', 'Birthday', 'Wedding', 'Home'],
    },
    {
      key: 'material',
      label: 'Material',
      type: 'text',
      section: 'technical',
      placeholder: 'Plastic, Glass, Ceramic, Wood, Metal',
    },
    {
      key: 'dimensions',
      label: 'Dimensions',
      type: 'text',
      section: 'technical',
      placeholder: '25 x 10 x 8 cm',
    },
    {
      key: 'packQuantity',
      label: 'Pack Quantity',
      type: 'text',
      section: 'technical',
      placeholder: '1 Piece, Set of 3, Pack of 6',
    },
    {
      key: 'features',
      label: 'Features',
      type: 'textarea',
      section: 'technical',
      placeholder: 'Reusable, compact, gift-ready, durable',
    },
    {
      key: 'careInstructions',
      label: 'Care Instructions',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Hand wash only / wipe clean / keep dry',
    },
    {
      key: 'condition',
      label: 'Condition',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['New', 'Open Box'],
    },
    {
      key: 'packageContents',
      label: 'Package Contents',
      type: 'textarea',
      section: 'commercial',
      placeholder: '1 x gift item, 1 x box',
    },
    {
      key: 'countryOfOrigin',
      label: 'Country of Origin',
      type: 'text',
      section: 'commercial',
      placeholder: 'China, UAE, India',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '25 x 18 x 10 cm',
    },
  ],
},
  {
  id: 'electronics-used-devices',
  title: 'Electronics & Used Devices',
  description: 'Certified refurbished electronics and pre-owned devices with condition grading.',
  backendCategoryId: 'cat1',
  badge: 'Refurbished',

  fields: [
    {
      key: 'deviceType',
      label: 'Device Type',
      type: 'select',
      section: 'catalog',
      required: true,
      options: ['Laptop', 'Mobile', 'Tablet', 'Console', 'Monitor', 'Accessory', 'Smartwatch', 'Other'],
    },
    {
      key: 'brand',
      label: 'Brand',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'Apple, Dell, HP, Samsung, Lenovo',
    },
    {
      key: 'model',
      label: 'Model',
      type: 'text',
      section: 'catalog',
      required: true,
      placeholder: 'MacBook Pro A1502, iPhone 13 Pro, Dell Latitude 5490',
    },
    {
      key: 'specSummary',
      label: 'Specification Summary',
      type: 'text',
      section: 'technical',
      placeholder: 'Core i5, 8GB RAM, 256GB SSD / 128GB / 6.1-inch',
    },
    {
      key: 'conditionGrade',
      label: 'Condition Grade',
      type: 'select',
      section: 'commercial',
      required: true,
      options: ['A+', 'A', 'B+', 'B', 'C'],
    },
    {
      key: 'batteryHealth',
      label: 'Battery Health',
      type: 'text',
      section: 'commercial',
      placeholder: '85%, 92%, Good, Service Recommended',
    },
    {
      key: 'cosmeticNotes',
      label: 'Cosmetic Notes',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Minor scratches on lid, clean screen, no cracks',
    },
    {
      key: 'functionalStatus',
      label: 'Functional Status',
      type: 'select',
      section: 'commercial',
      options: ['Fully Tested', 'Fully Working', 'Minor Defect', 'Needs Repair'],
    },
    {
      key: 'screenCondition',
      label: 'Screen Condition',
      type: 'text',
      section: 'commercial',
      placeholder: 'No dead pixels, light scratches, perfect display',
    },
    {
      key: 'includedItems',
      label: 'Included Items',
      type: 'textarea',
      section: 'commercial',
      placeholder: 'Original charger, cable, box, keyboard cover',
    },
    {
      key: 'lockedStatus',
      label: 'Locked Status',
      type: 'select',
      section: 'commercial',
      options: ['Unlocked', 'iCloud Free', 'Factory Reset', 'N/A'],
    },
    {
      key: 'warranty',
      label: 'Warranty',
      type: 'select',
      section: 'commercial',
      options: ['No Warranty', '7 Days', '30 Days', '90 Days', '6 Months', '1 Year'],
    },
    {
      key: 'serialInfo',
      label: 'Serial / Reference Info',
      type: 'text',
      section: 'technical',
      placeholder: 'Optional internal tracking reference',
    },
    {
      key: 'shippingWeight',
      label: 'Shipping Weight (kg)',
      type: 'number',
      section: 'logistics',
    },
    {
      key: 'packageSize',
      label: 'Package Size',
      type: 'text',
      section: 'logistics',
      placeholder: '35 x 25 x 10 cm',
    },
  ],
}
];

export const LISTING_TEMPLATE_MAP = Object.fromEntries(
  LAUNCH_LISTING_TEMPLATES.map((template) => [template.id, template])
) as Record<string, ListingTemplate>;

export const listingSectionLabels: Record<ListingFieldDefinition['section'], string> = {
  catalog: 'Catalog Identity',
  technical: 'Technical Specifications',
  commercial: 'Commercial & Condition',
  logistics: 'Logistics',
};
