export {
  DEFAULT_SPECIFICATION_TEMPLATES,
  buildDetailedSpecificationGroups,
  buildFlatSpecifications,
  buildSpecificationTableRows,
  getEnabledSpecificationFields,
  getMissingRequiredSpecificationLabels,
  getSpecificationTemplate,
  getTemplateFieldMap,
  getTemplateVariantFields,
  humanizeSpecificationValue,
  normalizeSpecificationValue,
  normalizeSpecificationValues,
  preserveMatchingSpecificationValues,
  type DetailedSpecificationGroup,
  type DetailedSpecificationItem,
  type SpecificationFieldDefinition,
  type SpecificationFieldType,
  type SpecificationTemplate,
  type SpecificationValue,
  type VariantDimensionKey,
} from '../../shared/productSpecifications';
